version: '3'

services:
  db:
    container_name: db
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data

  api:
    container_name: api
    image: docker.pkg.github.com/robin-copy/api/robin-copy-api-development:latest
    environment:
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432


  client:
    container_name: client
    image: docker.pkg.github.com/robin-copy/client-web/robin-copy-client-develop:latest

  revproxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - 3000:80

volumes:
  data:
    external: true
